--DDL CRIACAO DA TABELA PARA NOSSO LABORATORIO 

CREATE TABLE FUNCIONARIOS 
(
ID INT NOT NULL,
NOME VARCHAR2(50) NOT NULL,
SALARIO DECIMAL(10,2),
SETOR VARCHAR2(30), 
PRIMARY KEY (ID)
);

CREATE SEQUENCE ID_FUNC
START WITH 1 
INCREMENT BY 1
NOCACHE;

--DML SELECT 
--EXEMPLO SELECT 
SELECT* FROM FUNCIONARIOS;

-- EXEMPLO SELECT 
SELECT ID, NOME, SALARIO, SETOR AS DEPTO
FROM FUNCIONARIOS;

-- DML INSERT 
INSERT INTO FUNCIONARIOS (ID,NOME,SALARIO) VALUES 
    (id_func.nextval, 'PEDRO', 1000);
INSERT INTO FUNCIONARIOS (ID,NOME,SALARIO) VALUES 
    (id_func.nextval, 'CLEITON R.', 1080);
INSERT INTO FUNCIONARIOS (ID,NOME,SALARIO) VALUES 
    (id_func.nextval, 'JOAO', 1000);
INSERT INTO FUNCIONARIOS (ID,NOME,SALARIO) VALUES 
    (id_func.nextval, 'FABIO ROOTS', 3000);
INSERT INTO FUNCIONARIOS (ID,NOME,SALARIO) VALUES 
    (id_func.nextval, 'JOSE', 2000);

-- DML IPDATE 
UPDATE FUNCIONARIOS SET SALARIO = 1500
WHERE ID = 5;

-- OU AUMENTO DE 50% SOBRE SALARIO ATUAL
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.5
WHERE ID ='6';

-- EXEMPLO UPDATE COM MAIS DE UM CAMPO 
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.5, SETOR = 'TI'
WHERE ID <> '5';

-- DML DELETE 
DELETE 
FROM FUNCIONARIOS 
WHERE ID = '5';

SELECT ID, NOME, SALARIO, SETOR
FROM FUNCIONARIOS;