--DDL CRIANDO TABELA 

CREATE TABLE FUNCIONARIO 
(
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    SOBRENOME VARCHAR2(50) NOT NULL,
    ENDERECO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    PAIS VARCHAR2(50),
    DATA_NASC DATE --TIMESTAMP POSSIVEL TAMBEM 
);

--DDL SEQUENCIA FUNCIONARIO 
CREATE SEQUENCE ID_FUNC2
 START WITH 1
 INCREMENT BY 1
 NOCACHE;
 
--DDL CRIANDO TABELA COM CHAVE ESTRANGEIRA 
CREATE TABLE SALARIO 
(
    MATRICULA INT NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL,
    FOREIGN KEY(MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);

-- DDL CRIACAO DA TABELA COM CHAVE PRIMARIA 
CREATE TABLE AUDIT_SALARIO
(
    TRANSACAO INT NOT NULL,
    MATRIUCLA INT NOT NULL,
    DATA_TRANS TIMESTAMP NOT NULL,
    SAL_ANTIGO DECIMAL(10,2),
    SAL_NOVO DECIMAL(10,2),
    USUARIO VARCHAR2(20) NOT NULL,
    PRIMARY KEY (TRANSACAO),
    FOREIGN KEY(MATRIUCLA) REFERENCES FUNCIONARIO(MATRICULA)
);

-- DDL SEQUENCIA TRANSACAO 
CREATE SEQUENCE ID_TRAN 
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

--DDL CRIACAO DE INDEX 
CREATE INDEX IX_FUNC1 ON FUNCIONARIO(DATA_NASC);

--DDL CRIACAO DE INDEX 
CREATE INDEX IX_FUNC2 ON FUNCIONARIO(CIDADE, PAIS);

--ADICIONANDO NOVO CAMPO NA TABELA
ALTER TABLE FUNCIONARIO ADD GENERO CHAR(1);

--SELECT * FROM FUNCIONARIO;

--RENOMEANDO CAMPO/COLUNAS DA TABELA 
ALTER TABLE FUNCIONARIO RENAME COLUMN GENERO TO SEXO;

-- MODIFICANDO TIPO CAMPO
ALTER TABLE FUNCIONARIO MODIFY SEXO VARCHAR2(1);

--RENOMEANDO TABELA 
ALTER TABLE FUNCIONARIO 
RENAME TO PESSOA;

--RETORNANDO SITUACAO ANTERIOR 
ALTER TABLE PESSOA 
RENAME TO FUNCIONARIO;

--DDL PARA ADICIONAR COLUNA NA TAB SENSO
ALTER TABLE SENSO ADD ID INT;

-- DDL PARA REMOVER CAMPO ID DA TABELA SENSO 
ALTER TABLE SENSO 
DROP COLUMN ID;

-- SELECT * FROM SENSO;

-- ALTERANDO TIPO DA COLUNA 
ALTER TABLE FUNCIONARIO MODIFY ENDERECO VARCHAR2(30);

--EXCLUINDO CAMPO DA COLUNA 
ALTER TABLE FUNCIONARIO DROP COLUMN SEXO;

-- DDL CRIACAO DE DATABASE 
CREATE DATABASE TESTE;

--EXCLUINDO DATABASE
DROP DATABASE TESTE;

--Excluindo TABLE 
DROP TABLE SALARIO;

--LIBREANDO ACESSO PARA CRIAÇÃO DE VIEWS
GRANT CREATE VIEW TO ALUNO;

--CRIACAO DE VIEW 
CREATE VIEW V_FUNCIONARIO
    AS 
    SELECT * FROM FUNCIONARIOS;

--MODIFICANDO VIEW DE VIEW
--ALTER VIEW 
    CREATE OR REPLACE VIEW V_FUNCIONARIO 
    AS 
    SELECT ID, NOME FROM FUNCIONARIOS;
    
--EXCLUINDO VIEW
DROP VIEW V_FUNCIONARIO;

--EXCLUINDO INDEX
DROP INDEX IX_FUNC1;

-- CRIANDO INDEX
CREATE INDEX IX_FUNC1 ON FUNCIONARIOS(NOME);

-- CRIANDO PROCEDURE 
CREATE OR REPLACE PROCEDURE PROC_QUADRADO (V_NUM1 NUMBER)
IS
V_NUM2 NUMBER;
BEGIN 
    V_NUM2 := V_NUM1 * V_NUM1;
    DBMS_OUTPUT.PUT_LINE('RETORNO: ' || V_NUM2);
END;

-- EXECUTANDO A PROCEDURE
SET SERVEROUTPUT ON;
EXECUTE PROC_QUADRADO (10);

--EXCLUINDO PROCEDURE
DROP PROCEDURE PROC_QUADRADO;

--EXCLUINDO FUNÇÃO EXEMPLO
DROP FUNCTION FUNC_SALARIO;

--EXCLUINDO TRIGGER
DROP TRIGGER TRIG_FUNC_SALARIO;

--DDL TRUNCATE
TRUNCATE TABLE SENSO;

--DDL TRAUNCATE VERICIANDO REGISTROS
SELECT * FROM FUNCIONARIOS;

--CRIANDO TABELA TEMPORARIA BK EM TABELA TEMPORARIA
CREATE GLOBAL TEMPORARY TABLE TMP_FUNCIONARIOS
(
    ID INT,
    NOME VARCHAR2(50),
    SALARIO DECIMAL (12,5),
    SETOR VARCHAR2(30)
);

-- FAZENDO BK NA TABELA TEMPORARIA 
INSERT INTO TMP_FUNCIONARIOS
SELECT * FROM FUNCIONARIOS;

-- VERIFICANDO BK NA TABELA TEMPORARIA
SELECT * FROM TMP_FUNCIONARIOS;