--CONCEDE - GRANT 
-- CRIA UM LOGIN "ALUNO" E SEDE PERMISSÕES NO BANCO E OBJETOS 

--CONCEDENDO ACESSO DE ATUALIZACAO PARA ALUNO.
GRANT UPDATE ON ALUNO.FUNCIONARIOS TO ALUNO;

--CONSEDE ACESSO DE ATUALIZACAO PARA ALUNO COM WITH ADMIN OPTION
--USUÁRIO ALUNO PODE ESTENDER SEUS PRIVILÉGIOS DE SISTEMA PARA OUTROS USUÁRIOS.
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW TO ALUNO WITH ADMIN OPTION;

--CONCEDENDO ACESSO DE UPDATE, SELECT PARA ALUNO EM TODOS OS OBJETOS 
GRANT SELECT, UPDATE ON ALUNO.SENSO TO ALUNO;

--CONCEDENDO ACESSO DE INSERT, DELETE PARA ALUNO EM TODOS OS OBJETOS
GRANT INSERT, DELETE ON ALUNO.SENSO TO ALUNO;

--CONCEDENDO ACESSO DE INSERT, DELTE PARA ALUNO EM TODOS OBJETOS
GRANT CREATE PROCEDURE, CREATE VIEW TO ALUNO;

-- DICA PARA GERAR GRANTS PARA MUITOS OBJETOS
SELECT 'GRANT ALL ON ' || OBJECT_NAME || ' TO ALUNO;' AS RETORNO
    FROM USER_OBJECTS;

SELECT 'GRANT UPDATE ON ' || OBJECT_NAME || ' TO ALUNO;' AS RETORNO 
    FROM USER_OBJECTS
    WHERE OBJECT_TYPE='TABLE';

--EXEMPLO 
GRANT UPDATE ON HELP TO ALUNO;

-- CONCEDENDO ACESSO DE DELETE PARA ALUNO 
GRANT DELETE ON ALUNO.FUNCIONARIOS TO ALUNO;

--CONCEDENDO ACESSO DE DELETE PARA ALUNO EM TODOS OBJETOS
GRANT DELETE ON ALUNO.SENSO TO ALUNO;

--CONCEDENDO ACESSO DE INSERT PARA ALUNO.
GRANT INSERT ON ALUNO.FUNCIONARIOS TO ALUNO;

--CONCEDENDO COM LIMITAÇÃO DE CAMPOS 
GRANT INSERT (NOME, SETOR) ON ALUNO.FUNCIONARIOS TO ALUNO;

GRANT UPDATE (NOME, SETOR) ON ALUNO.FUNCIONARIOS TO ALUNO;

--CONCEDENDO ACESSO PARA EXECUTAR PROC PROC_QUADRADO PARA ALUNO
GRANT EXECUTE ON ALUNO.PROC_QUADRADO TO ALUNO;

--CONHECEDENDO TODOS ACESSOS A TODOS OBJETOS
GRANT ALL ON ALUNO.FUNCIONARIOS TO ALUNO;

--VEREIFICANDO PREVILEGIOS
-- VERIFICAR PELO SYSTEM

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'ALUNO';

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE LIKE 'ALUNO';

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE 'ALUNO';

SELECT *  FROM USER_TAB_PRIVS;

-- PARTE II MEGA-REVOKE
SELECT USER FROM DUAL;

--ANALISANDO 
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'ALUNO';

--REVOGANDO 
REVOKE CREATE VIEW, CREATE PROCEDURE, CREATE SESSION, CREATE TABLE ALUNO;

--CONCEDENDO 
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SESSION, CREATE TABLE TO ALUNO;

--ANALISANDO 
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE LIKE 'ALUNO';

--REVOGANDO 
REVOKE RESOURCE FROM ALUNO;
REVOKE UPDATE FROM ALUNO;