--CRIANDO DE TESTE 

--CRIANDO TABELA DE TESTE
CREATE TABLE CADASTRO 
(
    NOME VARCHAR2(50) NOT NULL,
    DOCTO VARCHAR2(20) NOT NULL
);

--INSERE REGISTRO 
INSERT INTO CADASTRO VALUES ('JHOW', '12341244');
SAVEPOINT P1;
INSERT INTO CADASTRO VALUES ('GAZE', '958456');
SAVEPOINT P2;
INSERT INTO CADASTRO VALUES ('CATEROIDE', '267564');
SAVEPOINT P3;
--VERIFICANDO REGISTRO
SELECT NOME, DOCTO
FROM CADASTRO;

--RETORNA A TABELA PARA ESTADO ANTERIOR DO BEGIN TRANSACTION
--ROLLBACK;
ROLLBACK;

--RETORNA A TABELA PARA ESTADO ANTERIOR DO BEGIN TRANSACTION
ROLLBACK TO SAVEPOINT P2;

--EFETIVA AS INFROMAÇÕES NA TABELAS DO BANCO DE DAOS 
COMMIT;