select * from senso;
select * from uf;

-- AVG -> RETORNA A MÉDIA DOS VALORES EM UM GRUPO. VALORES NULOS SÃO IGNORADOS
SELECT AVG(POPULACAO) AS MEDIA 
FROM SENSO
WHERE ANO = '2014';

-- AVG -> RETORNA A MÉDIA DOS VALORES EM UM GRUPO. VALORES NULOS SÃO IGNORADOS
SELECT ESTADO, AVG(POPULACAO) AS MEDIA 
FROM SENSO
WHERE ANO = '2014'
GROUP BY ESTADO
ORDER BY 2 DESC;

-- AVG MEDIA POR ESTACOM COM SIGLA ESTADO
SELECT A.COD_UF, B.SIGLA_UF, AVG(A.POPULACAO) MEDIA
FROM SENSO A 
INNER JOIN UF B
ON A.COD_UF = B.COD_UF
WHERE A.ANO = '2014'
GROUP BY A.COD_UF, B.SIGLA_UF
ORDER BY 3 DESC;

--AVG POR REGIAO
--AVG MEDIA POR REGIAO
SELECT A.REGIAO, AVG(A.POPULACAO)
FROM SENSO A 
WHERE A.ANO = '2014'
GROUP BY A.REGIAO
ORDER BY 2 DESC;

-- MIN RETORNA O VALOR MÍNIMO NA EXPRESSÃO. PODE SER SEGUIDO PELA CLAUSULA OVER
SELECT MIN(A.POPULACAO) 
FROM SENSO A
WHERE A.ANO = '2014';

-- MIN POR ESTADO 
SELECT A.ESTADO, MIN(A.POPULACAO)
FROM SENSO A 
WHERE A.ANO = '2014'
GROUP BY ESTADO;

-- MIN POR POPULACAO
SELECT A.REGIAO, MIN(POPULACAO)
FROM SENSO A
WHERE A.ANO = '2014' 
GROUP BY A.REGIAO
ORDER BY 2;

--MAX RETORNA O VALOR MÁXIMO NA EXPRESSÃO 
SELECT MAX(A.POPULACAO)
FROM SENSO A
WHERE A.ANO = '2014';

-- MAX POR ESTADO 
SELECT A.ESTADO, MAX(A.POPULACAO)
FROM SENSO A 
WHERE A.ANO = '2014'
GROUP BY A.ESTADO 
ORDER BY 2 DESC;

--MAX POR SIGLA ESTADO 
SELECT B.SIGLA_UF, MAX(A.POPULACAO) AS MAXIMO
FROM SENSO A  
INNER JOIN UF B 
ON A.COD_UF = B.COD_UF
WHERE A.ANO = '2014'
GROUP BY B.SIGLA_UF
ORDER BY 2;

-- COUNT RETORNA O NÚMRO DE ITENS DE UM GRUPO 
SELECT COUNT(*) 
FROM SENSO A
WHERE A.ANO = '2014';

-- COUNT RETORNA O NÚMERO DE CIADADE POR ANO 
SELECT A.ANO, COUNT(*) QTD_CIDADES 
FROM SENSO A 
GROUP BY A.ANO;

-- COUNT RETORNA O NÚMERO DE CIDADE POR ANO 
SELECT A.ANO, COUNT(*) QTD_CIDADES 
FROM SENSO A
GROUP BY A.ANO
ORDER BY 1 ASC;

-- DESCOBRINDO QTD ESTADOS 
SELECT COUNT(DISTINCT COD_UF) 
FROM SENSO;

-- EXEMPLO
SELECT COUNT(COD_UF) 
FROM SENSO;

-- COUNT POR ESTADO 
SELECT A.ESTADO, COUNT(*) 
FROM SENSO A
WHERE ANO = '2014'
GROUP BY A.ESTADO
ORDER BY 2 DESC;

-- COUNT POR REGIAO 
SELECT A.REGIAO, COUNT(*) 
FROM SENSO A 
WHERE ANO = '2014'
GROUP BY A.REGIAO
ORDER BY 2 DESC;

-- USANDO VARIAS FUNCOES DE AGREGACAO
SELECT AVG(A.POPULACAO) MEDIA_POP,
       MIN(A.POPULACAO) MINIMO_POP,
       MAX(A.POPULACAO) MAXIMO_POP,
       SUM(A.POPULACAO) TOTAL_POP,
       COUNT(*) QTD_CIDADES
FROM SENSO A
WHERE A.ANO = '2014';

-- POR ESTADO
SELECT A.ESTADO,
       AVG(A.POPULACAO) MEDIA_POP,
       MIN(A.POPULACAO) MINIMO_POP,
       MAX(A.POPULACAO) MAXIMO_POP,
       SUM(A.POPULACAO) TOTAL_POP,
       COUNT(*) QTD_CIDADES
FROM SENSO A 
WHERE A.ANO = '2014'
GROUP BY A.ESTADO
ORDER BY 2 DESC;

-- APRESENTAR NOME DA CIDADE COM MAIOR POPULACAO DE CADA ESTADO 
SELECT A.ESTADO, A.NOME_MUN, A.POPULACAO
FROM 
 (
    SELECT B.ESTADO, MAX(B.POPULACAO) AS POPULACAO 
    FROM SENSO B
    GROUP BY B.ESTADO
 ) B
 JOIN SENSO A 
 ON  A.ESTADO    = B.ESTADO
 AND A.POPULACAO = B.POPULACAO
 WHERE    A.ANO  = '2014'
 ORDER BY A.POPULACAO DESC;
 
-- APRESENTAR NOME DA CIDADE COM MINIMO POPULACAO DE CADA ESTADO 
SELECT A.ESTADO, A.NOME_MUN, A.POPULACAO
FROM 
 (
    SELECT B.ESTADO, MIN(B.POPULACAO) AS POPULACAO 
    FROM SENSO B
    GROUP BY B.ESTADO
 ) B
 JOIN SENSO A 
 ON  A.ESTADO    = B.ESTADO
 AND A.POPULACAO = B.POPULACAO
 WHERE    A.ANO  = '2014'
 ORDER BY A.POPULACAO DESC;
 
-- STDDEV RETORNA O DESVIO PADRÃO ESTATÍSTICO DE TODOS OS VALORES DA EXPRESSÃO ESPECIFICADA
SELECT STDDEV(A.POPULACAO) 
FROM SENSO A
WHERE A.ANO = '2014';

-- COMPARANDO CRESCIMENTO POP DA CIDADES REF ANOS 2010 A 2014
-- SELECT COD_UF, COD_UF+COD_MUN AS CONCATENADO FROM CIDADES
SELECT A.NOME_MUN, A.POPULACAO AS SENSO_2010,
       B.POPULACAO             AS SENSO_2014,
       (100/A.POPULACAO)*(B.POPULACAO)-100 AS PERCENTUAL
FROM SENSO A
INNER JOIN SENSO B
ON A.COD_MUN = B.COD_MUN
WHERE A.ANO = '2010'
AND B.ANO = '2014';

-- COMPARANDO CRESCIMENTO POPULACAO DA ESTADO REF ANOS 2010 A 2014
SELECT A.ESTADO,
       SUM(A.POPULACAO) AS SENSO_2010,
       SUM(B.POPULACAO) AS SENSO_2014,
       (100/SUM(A.POPULACAO))*(SUM(B.POPULACAO))-100 AS PERCENTUAL
FROM SENSO A 
INNER JOIN SENSO B
ON A.COD_MUN = B.COD_MUN
WHERE A.ANO = '2010'
AND B.ANO = '2014'
GROUP BY A.ESTADO;

-- VAR_POP RETORNAR A VARIÂNCIA ESTATÍSTICA DE TODOS OS VALORES DA EXPRESSÃO ESPECIFICADA
SELECT VAR_POP(POPULACAO) FROM SENSO;

-- VAR_SAMP COM GROUP BY
SELECT ESTADO, VAR_SAMP(POPULACAO) 
FROM SENSO 
GROUP BY ESTADO;