
--SUBSELECT

--DESCOBRIR TODOS OS ATORES QUE FIZERAM O FILME COM SEGUINTES PARAMETROS 
-- FILM = 1 COM TITLE = ACADEMY DINOSAUR
-- CONHECER A ESTRUTURA DAS TABELAS ALVO

SELECT * FROM HR.EMPLOYEES;
SELECT * FROM HR.JOB_HISTORY;
SELECT * FROM HR.DEPARTMENTS;
SELECT * FROM HR.JOBS;

--EXEMPLO DE SUBSELECT 1 OPERADOR IN
SELECT * FROM HR.EMPLOYEES A 
WHERE A.EMPLOYEE_ID IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B);

--EXEMPLO DE SUBSELECT 2 OPERADOR IN 
SELECT *  
FROM HR.EMPLOYEES A 
WHERE A.MANAGER_ID = '100' 
AND A.EMPLOYEE_ID IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B);

--EXEMPLO DE SUBSELECT 3 OPERADOR IN
SELECT *
FROM HR.EMPLOYEES A 
WHERE A.EMPLOYEE_ID IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B
                        WHERE B.DEPARTMENT_ID = '50');
                        
-- EXEMPLO DE SUBSELECT 5 OPERADOR NOT IN
SELECT * 
FROM HR.EMPLOYEES A 
WHERE A.EMPLOYEE_ID NOT IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B);

-- EXEMPLO DE SUBSELECT 5 OPERADOR NOT IN 
SELECT *
FROM HR.EMPLOYEES A 
WHERE A.MANAGER_ID = '100'
AND A.EMPLOYEE_ID NOT IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B);

-- EXEMPLO DE SUBSELECT 3 OPERADOR NOT IN 
SELECT * 
FROM HR.EMPLOYEES A 
WHERE A.EMPLOYEE_ID NOT IN (SELECT B.EMPLOYEE_ID FROM HR.JOB_HISTORY B
                            WHERE B.DEPARTMENT_ID = '50');
                            
--SUBSELECT RETORNANDO COLUNA 
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.JOB_ID,
(   SELECT B.JOB_TITLE 
    FROM   HR.JOBS B 
    WHERE  A.JOB_ID = B.JOB_ID   ) AS CARGO
FROM HR.EMPLOYEES A
ORDER BY 1;

--SUBSELECT RETORNANDO COLUNA 
SELECT A.EMPLOYEE_ID, A.FIRST_NAME, A.DEPARTMENT_ID,
    (SELECT B.DEPARTMENT_NAME FROM HR.DEPARTMENTS B 
        WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) AS DEPTO
FROM HR.EMPLOYEES A;

-- SUBSELECT RETORNANDO COLUNA 
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, A.MANAGER_ID, 
(    SELECT B.FIRST_NAME 
     FROM HR.EMPLOYEES B 
     WHERE A.MANAGER_ID = B.EMPLOYEE_ID  ) AS NOME_GER
FROM HR.DEPARTMENTS A;

--SUBSELECT COM VALOR AGREGADO SOMA 
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME,
    (SELECT SUM(B.SALARY) 
     FROM HR.EMPLOYEES B 
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) SALARIO_DEPTO
FROM HR.DEPARTMENTS A;

--SUBSELECT COM VALOR AGREGADO SOMA 
SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME,
    (SELECT SUM(B.SALARY) 
     FROM HR.EMPLOYEES B 
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) SALARIO_DEPTO,
    (SELECT COUNT(*) 
     FROM HR.EMPLOYEES B 
     WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) QTD_FUNC
FROM HR.DEPARTMENTS A;

--SELECT
SELECT A.DEPARTMENT_ID,
       A.DEPARTMENT_NAME,
--CALCULO TOTAL SALARIO
(SELECT SUM(B.SALARY) FROM HR.EMPLOYEES B WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) SALARIO_DEPTO,
--CALCULO QTD FUNCIONARIO
(SELECT COUNT(*) FROM HR.EMPLOYEES B WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) QTD_FUNC,
--MEDIA
(SELECT SUM(B.SALARY) FROM HR.EMPLOYEES B WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) / -- OPERADOR MATEMATICO
(SELECT COUNT(*) FROM HR.EMPLOYEES B WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID) MEDIA
FROM HR.DEPARTMENTS A;