--CRIANDO TABLESPACE 
CREATE TABLESPACE CURSO
DATAFILE 
 'C:\oraclexe\app\oracle\oradata\XE\curso.dbf'
    SIZE 100m AUTOEXTEND ON NEXT 50m MAXSIZE 500m
    ONLINE
    PERMANENT
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    SEGMENT SPACE MANAGEMENT AUTO;

 -- CRIANDO USUARIO
 CREATE USER ALUNO 
        IDENTIFIED BY ALUNO 
        DEFAULT TABLESPACE CURSO
        TEMPORARY TABLESPACE TEMP;
 -- PERMISSAO PARA ALUNO 
 GRANT CREATE SESSION, CONNECT, RESOURCE TO ALUNO;
 
 ALTER USER ALUNO QUOTA UNLIMITED ON CURSO;