-- Acesso de select para usuario aluno nas tabelas abaixo:

SELECT USER FROM DUAL;

-- executar os grants na tablespace ORA_XE
GRANT SELECT ON  HR.COUNTRIES TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.DEPARTMENTS TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.EMPLOYEES TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.JOB_HISTORY TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.JOBS TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.LOCATIONS TO ALUNO WITH GRANT OPTION;
GRANT select ON  HR.REGIONS TO ALUNO WITH GRANT OPTION;

--EXEMPLO OPERADOR IGUAL =
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES emp
WHERE emp.JOB_ID = 'IT_PROG';

--EXEMPLO OPERADOR IGUAL = 
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES emp
WHERE emp.SALARY = '9000';

--EXEMPLO OPERADOR MAIOR >
SELECT emp.FIRST_NAME "NOME", emp.LAST_NAME "SOBRENOME", EMAIL, PHONE_NUMBER,
       HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES emp
WHERE emp.HIRE_DATE > '03/01/06';

--EXEMPLO OPERADOR MAIOR >
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID 
FROM HR.EMPLOYEES hr 
WHERE hr.SALARY > '9000';

--EXEMPLO OPERADOR MENOR <
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr 
WHERE hr.HIRE_DATE < '03/02/06'
order by hr.HIRE_DATE ASC;

--EXEMPLO OPERADOR MENOR <
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr 
WHERE hr.HIRE_DATE < '03/02/06'
order by hr.HIRE_DATE DESC;

--EXEMPLO OPERADOR MENOR <
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr
where hr.SALARY < '9000';

--EXEMPLO OPERADOR MAIOR IGUAL >=
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr
WHERE hr.SALARY >= '9000'
ORDER BY hr.SALARY ASC;

--EXEMPLO OPERADOR MAIOR IGUAL >=
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr
WHERE hr.SALARY >= '9000'
ORDER BY hr.SALARY DESC;

--EXEMPLO OPERADOR MAIOR IGUAL >= 
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES a
WHERE a.HIRE_DATE >= '03/02/06';

--EXEMPLO OPERADOR MENOR IGUAL <=
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr 
WHERE hr.SALARY <= '9000'
ORDER BY hr.SALARY ASC;

--EXEMPLO OPERADOR MENOR IGUAL <=
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr 
WHERE hr.SALARY <= '9000'
ORDER BY hr.SALARY DESC;

--EXEMPLO OPERADOR DIFERENTE <>
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr
WHERE hr.JOB_ID <> 'IT_PROG';

--EXEMPLO OPERADOR DIFERENTE <>
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr
WHERE hr.MANAGER_ID <> '108';

--EXEMPLO COMBINANDO OPERADORES
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY,
       MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES hr 
WHERE hr.JOB_ID = 'IT_PROG'
AND   hr.SALARY > 4800
AND   hr.MANAGER_ID = '103';

