--OPERADOR DE ADICAO +
SELECT 3 + 2 AS RESULTADO FROM DUAL;

SELECT emp.FIRST_NAME, emp.SALARY, emp.SALARY+530 AS SALARIO_NOVO
FROM HR.EMPLOYEES emp;

--OPERADOR DE SUBTRACAO
SELECT 1-3 AS RESULTADO FROM DUAL;

SELECT 7-4 AS RESULTADO FROM DUAL;

SELECT emp.FIRST_NAME, 
       emp.SALARY, 
       emp.SALARY-530 AS SALARIO_NOVO
FROM HR.EMPLOYEES emp;

--OPERADOR DE MULTIPLICAÇÃO 
SELECT 2*3 AS RESULTADO FROM DUAL;

SELECT 7*4 AS RESULTADO FROM DUAL;

SELECT (7*4)*-1 AS RESULTADO FROM DUAL;

SELECT hr.FIRST_NAME, hr.SALARY, hr.SALARY*1.10 AS SALARIO_NOVO
FROM HR.EMPLOYEES hr;

SELECT a.FIRST_NAME, a.SALARY, a.SALARY*0.10 AS valor_acresc, 
       a.SALARY*1.10 AS salario_novo
FROM HR.EMPLOYEES a; 

--OPERADOR DE DIVISAO /
SELECT 2/4 AS RESULTADO FROM DUAL;

SELECT 4/2 AS RESULTADO FROM DUAL;

SELECT a.FIRST_NAME, a.SALARY, a.SALARY/10 AS SALARIO_NOVO
FROM HR.EMPLOYEES a;

--OPERADOR MOD %

SELECT MOD(10,5) AS RESULTADO FROM DUAL;

SELECT MOD(10,3) AS RESULTADO FROM DUAL;

--EXPRESSÕES 

SELECT 2*4/3+3 FROM DUAL;

SELECT ((2*4)/3) + 3 FROM DUAL;