
/*criação da tabela senso*/
CREATE TABLE SENSO
(
ANO INT NOT NULL,
COD_UF CHAR(2) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
COD_MUN CHAR(7) NOT NULL,
NOME_MUN VARCHAR(50) NOT NULL,
REGIAO VARCHAR(150),
COD_MESO_REG CHAR(4),
NOME_MESO_REG VARCHAR(100) NOT NULL,
COD_MIC_REG CHAR(5) NOT NULL,
NOME_MIN_REG VARCHAR(50) NOT NULL,
PIB DECIMAL(12,3) NOT NULL,
POPULACAO INTEGER NOT NULL,
PIB_PER_CAP DECIMAL(12,3) NOT NULL
);

CREATE TABLE UF
(
COD_UF CHAR(2) NOT NULL PRIMARY KEY, 
SIGLA_UF CHAR(2) NOT NULL,
ESTADO VARCHAR(50) NOT NULL
);

SELECT * FROM SENSO;

SELECT * FROM UF;

-- OPERADOR WHERE
SELECT *
FROM SENSO
WHERE NOME_MUN = 'Jundiaí'
AND ANO = '2014';

-- OPERADOR AND 
SELECT * 
FROM SENSO
WHERE COD_UF = '35'
AND POPULACAO > 50000
AND ANO = '2014';

--OPERADOR BETWEEN
SELECT * FROM SENSO 
WHERE COD_UF = '35'
AND POPULACAO BETWEEN 5000 AND 10000
AND ANO = '2014'
ORDER BY POPULACAO DESC;

--OPERADOR IN 
SELECT * FROM SENSO
WHERE COD_UF IN ('35','12')
AND ANO = '2014';

--OPERADOR NOT IN
SELECT * FROM SENSO
WHERE COD_UF NOT IN ('35', '12')
AND ANO = '2014';

--LIKE LOCALIZA VALORES QUE CONTENHAM "OR" EM QUALQUER LUGAR 
SELECT * FROM SENSO
WHERE NOME_MUN LIKE ('%_or%')
AND ANO = '2014';

--LIKE ENCONTRA QUAISQUER VALORES QUE TENHAM "R" NA SEGUNDA POSIÇÃO
SELECT * FROM SENSO
WHERE NOME_MUN LIKE ('_r%')
AND ANO = '2014'
ORDER BY ESTADO DESC;

-- LIKE LOCALIZA VALORES QUE COMEÇAM COM "A" E TERMINA COM "O"
SELECT * FROM SENSO
WHERE NOME_mUN LIKE 'A%o'
AND ANO = '2014';

-- LIKE LOCALIZA VALORES QUE COMEÇAM COM "A" 
SELECT * FROM SENSO 
    WHERE NOME_MUN LIKE 'A%'
    AND ANO = '2014'
    ORDER BY NOME_MUN DESC;
    
-- OPERADOR LIKE CURINGA __
SELECT * FROM SENSO
    WHERE NOME_MUN LIKE '_ra%'
    AND ANO = '2014';
    
-- OPERADO NOT
SELECT * FROM SENSO 
WHERE NOME_MUN NOT LIKE ('A%')
AND COD_UF = 35
AND NOT POPULACAO < 40000
AND ANO = '2014'
ORDER BY POPULACAO DESC;

SELECT ANO, COD_UF, ESTADO, NOME_MUN, POPULACAO 
FROM SENSO
WHERE NOME_MUN NOT LIKE ('A%')
AND COD_UF = '35'
AND NOT POPULACAO < 40000
AND ANO = '2014';

SELECT ANO, COD_UF, ESTADO, NOME_MUN, POPULACAO
FROM SENSO 
WHERE NOME_MUN NOT LIKE ('A%')
AND COD_UF = '35'
AND NOT POPULACAO > 40000
AND ANO = '2014';

-- OPERADOR OR 
SELECT * FROM SENSO 
WHERE NOME_MUN LIKE ('A%')
AND (COD_UF = '35' OR COD_UF = '15')
ORDER BY NOME_MUN DESC;

-- EVIDENCIA DE ERRO 
SELECT * FROM SENSO 
WHERE NOME_MUN ('A%')
AND COD_UF = '35'
AND COD_UF = '15';

-- OPERADOR IS NOT NULL
SELECT * FROM SENSO 
WHERE REGIAO IS NOT NULL;

-- OPERADOR IS NULL
SELECT * FROM SENSO
WHERE REGIAO IS NULL;

-- OPERADOR HAVING
SELECT COD_UF, ESTADO, COUNT(*)QTD
FROM SENSO 
WHERE ANO = '2014'
GROUP BY COD_UF, ESTADO HAVING COUNT(COD_MUN) > 500;

SELECT COD_UF, ESTADO, COUNT(*)QTD
FROM SENSO 
WHERE ANO = '2014'
GROUP BY COD_UF, ESTADO HAVING COUNT(COD_MUN) <= 500
ORDER BY 3 DESC;

SELECT COD_UF, ESTADO, COUNT(COD_MUN)QTD, SUM(POPULACAO)
FROM SENSO
WHERE ANO = '2014'
GROUP BY COD_UF, ESTADO HAVING SUM(POPULACAO) > 5000000;

SELECT COD_UF, ESTADO, COUNT(COD_MUN)QTD, SUM(POPULACAO)SOMA_POPULACAO
FROM SENSO
WHERE ANO = '2014'
GROUP BY COD_UF, ESTADO HAVING SUM(POPULACAO) < 5000000;