--EXEMPLOS DE UNION ALL

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES
ORDER BY 1;

--EXEMPLOS DE UNION
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM HR.EMPLOYEES 
UNION 
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM HR.EMPLOYEES
ORDER BY 1;

--SIMULANDO ERRO 1
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES
UNION 
SELECT EMPLOYEE_ID, FIRST_NAME 
FROM HR.EMPLOYEES
ORDER BY 1;

--SIMULANDO ERRO 2
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES 
UNION 
SELECT EMPLOYEE_ID, SALARY, FIRST_NAME 
FROM HR.EMPLOYEE
ORDER BY 1;

--CAMPOS DIFERENTES MAS COM MESMO TIPO -> ATRIBUTO EX.: VARCHAR2 = VARCHAR2
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY 
FROM HR.EMPLOYEES
UNION 
SELECT EMPLOYEE_ID, LAST_NAME, SALARY 
FROM HR.EMPLOYEES
ORDER BY 1;

-- SIMULANDO ERRO UNION
SELECT '1', '1', 'ABC' 
FROM DUAL 
UNION
SELECT 'A', 2 
FROM DUAL;

--EXEMPLO UNION ALL 
SELECT 'A' AS CAMPO1, 'B' AS CAMPO2 
FROM DUAL
UNION ALL
SELECT 'A' AS CAMPO3, 'B' AS CAMPO4
FROM DUAL;

--EXEMPLO UNION  
SELECT 'A' AS CAMPO1, 'B' AS CAMPO2 
FROM DUAL
UNION 
SELECT 'A' AS CAMPO3, 'B' AS CAMPO4
FROM DUAL;

--EXEMPLO USANDO UNION 
SELECT ANO, ESTADO
FROM SENSO
WHERE ANO = '2014'
UNION 
SELECT ANO, ESTADO
FROM SENSO
WHERE ANO ='2013'
ORDER BY ESTADO DESC;

--EXEMPLO USANDO UNION ALL
SELECT ANO, ESTADO
FROM SENSO
WHERE ANO = '2014'
UNION ALL
SELECT ANO, ESTADO
FROM SENSO
WHERE ANO ='2013'
ORDER BY ESTADO DESC;

-- EXEMPLO COM UNION 
SELECT ANO, ESTADO, NOME_MUN, POPULACAO
FROM SENSO 
WHERE ANO = '2014' 
AND COD_UF = '11'
UNION 
SELECT ANO, ESTADO, NOME_MUN, POPULACAO
FROM SENSO
WHERE ANO ='2013'
AND COD_UF = '11'
ORDER BY NOME_MUN, ANO DESC;